### ISSUE TITLE
Servo info

### ISSUE THREAD

**Issue by codeclinic** [sjchiass/trilobot_controls#1]
Hi, 
This looks exactly what I need to get my kids started with trilobot. I notice there is a control and corresponding code for a cat treat throwing servo. Could you possibly add some info on which servo and how this was setup?

Thanks!

**Comment by sjchiass** [comment]
Hey,
Sorry about the very sparse repo. I have a [blog post here](https://sjchiass.com/robot-remote-control-by-python-gui.html#robot-remote-control-by-python-gui) with more info. Also [this one](https://sjchiass.com/nightvision-robot.html#nightvision-robot) and [this one](https://sjchiass.com/adventures-of-fartbot.html#adventures-of-fartbot). I'm going to make a holiday activity out of sorting this information better.

I'll answer you directly here.

### Servos

I use [these kind of servo motors](https://www.amazon.com/Dorhea-Arduino-Helicopter-Airplane-Walking). They're a bit fragile but will do the job.

### Trilobot hookup

On the main Trilobot board (the one the motors are attached to), there is a header for a servo. If you have one of the servos above, they plug right in no problem.

I don't think that header comes pre-soldered so you'll have to do it yourself. Looks like they're not included with the Trilobot kit, so look to buy "single row straight headers" if you don't have them. If you don't have a soldering iron, you'll need one of those too.

You can see the header [in this image](https://cdn.learn.pimoroni.com/article/assembling-trilobot/assets/P1040768.jpg) that's part of the [Trilobot setup guide](https://learn.pimoroni.com/article/assembling-trilobot). `SIG - 5V - GND`

### Physical setup

On the top of the Trilobot (where the battery goes) I just put a piece of cardboard flat and ran the screws through it. This gives you a platform you can glue, screws or tie things without damaging the Trilobot.

In my case the servo is attached to the side of the cardboard with some zip ties. The servo is on its side.

The treat dispenser is extremely basic, just a rolled up piece of paper taped together. It makes a little container you can put treats in.

### Trilobot library

The Trilobot library has [some methods](https://github.com/pimoroni/trilobot-python/blob/main/examples/servo_control.py) for controlling the servo that's part of the main board. If you want to throw cat treats, start the treat container upright and then just flip it 180°. A treat is guaranteed to fly out. :laughing: 

### Python control

This is what you're seeing in the repo.

There are two options that I've found work well: control the bot "directly" through [an SSH session](https://github.com/sjchiass/trilobot_controls/blob/main/controls_ssh.py) or control it in [a separate GUI](https://github.com/sjchiass/trilobot_controls/blob/main/gui_local.py) through an API. A third option would be a web interface. I just have to learn how to stream the video.

<hr>

Hope that helps! If you want to some extra fun, set up a personal VPN so that you can easily connect to the Trilobot when you're away from home. You and your kids can then phone in and see what your pets are up to.

**Comment by codeclinic** [comment]
Thanks for taking the time to answer and give so much info. I really appreciate it.

I'm hoping to create a webGUI with my kids once we've got all the basics setup after Christmas. 

You may have already seen this but their is someone who has already created a basic [HTML page with streaming video](https://blog.piandpython.net/tag/trilobot/?utm_source=pocket_reader) that is all done with Python. From my quick glance it seems like it should be easy to expand upon. Especially since you appear to have done a lot of the work in terms of the controls.

I'm sure I could help with creating a webGUI once I've had time to play with Trilobot for a while.

(Have a great Christmas & New Year.)

**Comment by sjchiass** [comment]
Thanks for the link. I have to sit down and figure it out. A web GUI really would simplify the controls to just having the Raspberry Pi serving a webpage + API. Now that I think about it, it'd be a good solution for other gadgets...

Don't hesitate to reach out with questions or cool discoveries you want to share! Have a good Christmas + New Year! :santa:
